### ISSUE TITLE
Rectangle specs: discrepancy in the rounding method

### ISSUE THREAD

**Issue by mgrudzinska** [lottie/lottie-spec#82] opened 2024-08-09 12:27 UTC
<img width="593" alt="Zrzut ekranu 2024-08-9 o 13 48 27" src="https://github.com/user-attachments/assets/bbc6c4bd-57ad-4a44-a9fc-e1d6790c91ac">

To align with the results from AE (as well as SVG specs), the formula should take the following form:
``` max(min(s.x/2, r), min(s.y/2, r))```

sample:
[roundedRect.json](https://github.com/user-attachments/files/16561163/roundedRect.json)

**Comment by mbasaglia** [comment] 2024-08-09 12:42
So the issue is that SVG rounded rects have a different radius for the x and y directions, so each radius is clamped to half of the relevant size (`rx = min(rx, w/2)`,  `ry = min(ry, h/2)`.

Doing this in lottie would require internally splitting the rounded radius into x and y components.

Looks like AE does that under the hood but other lottie-related tools do not.

**Comment by mgrudzinska** [comment] 2024-08-09 16:53
we can achieve the expected result (same as in AE) using only one `r` value. lottie-web supports this, ThorVG can as well (https://github.com/thorvg/thorvg/pull/2627)

**Comment by hermet** [comment] 2024-08-10 04:20
skottie:
![image](https://github.com/user-attachments/assets/04ff62fd-3300-402d-b453-99d46d8f5426)

**Comment by mbasaglia** [comment] 2024-08-10 07:27
> skottie: [image]

That's unrelated since they aren't rectangles

**Comment by hermet** [comment] 2024-08-10 08:50
@mbasaglia One is rectangle there. LAC can expanding the topic about roundness and address the issues surrounding it.

**Comment by mbasaglia** [comment] 2024-08-10 09:52
Rounded polygons are a different feature to rounded rects, and they have been implemented in lottie-web for a long time

**Comment by mgrudzinska** [comment] 2024-08-12 09:46
as @hermet pointed out, ``` max(min(s.x/2, r), min(s.y/2, r))``` can be simplified to ``` min(r, max(s.x, s.y)/2)```

**Comment by b-wils** [comment] 2024-08-12 21:05
The example lottie is using the round corner modifier and not the roundness property of the rectangle shape. These behave differently, with the round corner modifier calculating each corner independently while the rectangle roundness property will use the formula in the spec. In AE, the latter formula is used for calculating the roundness as well-

![image](https://github.com/user-attachments/assets/e691062d-4fc2-42c0-905f-a490f4a34d11)

The round corner modifier is not a part of the 1.0 spec release but will be included in a future version. It will be good to document this behavior difference then.

**Closed** 2024-08-12 21:36 UTC
Labels: Draft Specs Comment
